name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: AutoPinkClicker-APK
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: |
          app/build/outputs/
          app/build/reports/
